version: "3"
services:
  application:
    image: dolmengate/bb-app:1.0-SNAPSHOT
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - mynetwork
networks:
  mynetwork:
